version: '3'

services:
  web:
    image: mea_publisher:latest
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-i", "-f", "http://localhost:3000/up"]
      interval: 10s
      timeout: 10s
      retries: 3
    env_file: .env

  postgres42:
    image: postgres:14.6-alpine
    volumes:
      - postgres_vol:/var/lib/postgresql/data:cached
      - ./dumps/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "mea_publisher_production"]
      interval: 5s
    env_file: .env

volumes:
  postgres_vol:
