version: '3'

services:
  web:
    image: mea_publisher:latest
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres@postgres42/mea_publisher_production
      - RAILS_LOG_TO_STDOUT=1

  postgres42:
    image: postgres:14.6-alpine
    volumes:
      - postgres_vol:/var/lib/postgresql/data:cached
      - ./dumps/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_vol:
